version: "2"

services:
  nginx:
    build: ./nginx
    logging:
      driver: "none"
    volumes:
      - ./nginx:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    # links:
    #   - node

  # node:
  #   build: ./node
  #   volumes:
  #     - ./node:/usr/src/app:ro
  #   ports:
  #     - "5858:5858"
